load_module /usr/lib/nginx/modules/ngx_http_dav_ext_module.so;

worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /run/nginx.pid;

events {
    worker_connections 2048;
    multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    charset utf-8;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;
    keepalive_requests 1000;

    server_tokens off;

    client_max_body_size 20M;
    client_body_timeout 120s;
    client_header_timeout 30s;
    send_timeout 120s;

    client_body_temp_path /tmp/nginx_upload;

    include /etc/nginx/conf.d/*.conf;
}